### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: saves/llama3-8b-instruct/lora/sft

### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
dataset: statqa_test
template: llama3
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b-instruct/lora/predict
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
