### model
model_name_or_path: meta-llama/Llama-2-7b-hf
adapter_name_or_path: saves/llama2-7b/lora/sft

### method
stage: sft
do_predict: true
finetuning_type: lora

### dataset
dataset: statqa_test
template: llama2
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama2-7b/lora/predict
overwrite_output_dir: true

### eval
per_device_eval_batch_size: 1
predict_with_generate: true
